/** Options for customising the generated wrangler config. */
export interface WranglerConfigOptions {
	/** Override the worker name (default: 'cf-monitor'). */
	name?: string;
	/** Override the AE dataset name (default: 'cf-monitor'). */
	dataset?: string;
	/** Human-readable account name (default: 'my-account'). */
	accountName?: string;
	/** GitHub repo for error issues (e.g. 'owner/repo'). */
	githubRepo?: string;
	/** Embedded cf-monitor.yaml as JSON (with $REFERENCES for secrets). */
	configJson?: string;
	/** Override the worker entry point (default: npm package path). */
	main?: string;
	/** Disable cron triggers (useful for test workers). */
	noCrons?: boolean;
}

/**
 * Generate the wrangler.jsonc config for the cf-monitor worker.
 */
export function generateWranglerConfig(
	accountId: string,
	kvNamespaceId: string,
	_isFree: boolean,
	options?: WranglerConfigOptions
): string {
	const workerName = options?.name ?? 'cf-monitor';
	const dataset = options?.dataset ?? 'cf-monitor';
	const accountName = options?.accountName ?? 'my-account';
	const githubRepo = options?.githubRepo;
	const configJson = options?.configJson;
	const main = options?.main ?? 'node_modules/@littlebearapps/cf-monitor/worker/index.ts';

	const crons = options?.noCrons ? [] : [
		'*/15 * * * *', // Gap detection
		'0 * * * *',    // Hourly metrics + budgets
		'0 0 * * *',    // Daily rollup + discovery
	];

	const config: Record<string, unknown> = {
		$schema: 'node_modules/wrangler/config-schema.json',
		name: workerName,
		main,
		compatibility_date: '2026-03-01',
		compatibility_flags: ['nodejs_compat_v2'],
		observability: { enabled: true },
		account_id: accountId,
		kv_namespaces: [
			{ binding: 'CF_MONITOR_KV', id: kvNamespaceId },
		],
		analytics_engine_datasets: [
			{ binding: 'CF_MONITOR_AE', dataset },
		],
		vars: {
			CF_ACCOUNT_ID: accountId,
			ACCOUNT_NAME: accountName,
			...(githubRepo ? { GITHUB_REPO: githubRepo } : {}),
			...(configJson ? { CF_MONITOR_CONFIG: configJson } : {}),
		},
	};

	if (crons.length > 0) {
		config.triggers = { crons };
	}

	return `// Auto-generated by cf-monitor CLI — edit cf-monitor.yaml instead
${JSON.stringify(config, null, 2)}
`;
}
