/**
 * Generate the wrangler.jsonc config for the cf-monitor worker.
 */
export function generateWranglerConfig(
	accountId: string,
	kvNamespaceId: string,
	_isFree: boolean
): string {
	const crons = [
		'*/15 * * * *', // Gap detection
		'0 * * * *',    // Hourly metrics + budgets
		'0 0 * * *',    // Daily rollup + discovery
	];

	const config = {
		$schema: 'node_modules/wrangler/config-schema.json',
		name: 'cf-monitor',
		main: 'node_modules/@littlebearapps/cf-monitor/worker/index.ts',
		compatibility_date: '2026-03-01',
		compatibility_flags: ['nodejs_compat_v2'],
		observability: { enabled: true },
		account_id: accountId,
		kv_namespaces: [
			{ binding: 'CF_MONITOR_KV', id: kvNamespaceId },
		],
		analytics_engine_datasets: [
			{ binding: 'CF_MONITOR_AE', dataset: 'cf-monitor' },
		],
		triggers: { crons },
		vars: {
			CF_ACCOUNT_ID: accountId,
			ACCOUNT_NAME: 'my-account',
		},
	};

	return `// Auto-generated by cf-monitor CLI — edit cf-monitor.yaml instead
${JSON.stringify(config, null, 2)}
`;
}
