import { KV } from '../../constants.js';
import type { MonitorWorkerEnv } from '../../types.js';
import type { WarningDigestEntry } from '../tail-handler.js';
import { createGitHubIssue } from '../errors/github.js';

/**
 * Daily midnight: Housekeeping tasks.
 * - Reset daily budget counters (KV TTL handles this naturally)
 * - Process P4 warning digest into a single GitHub issue
 * - Log daily summary to AE
 */
export async function runDailyRollup(env: MonitorWorkerEnv): Promise<void> {
	// Daily budget counters auto-expire via KV TTL (25hr).
	// No explicit reset needed — this is the beauty of KV-only storage.

	// Process warning digest — create single daily digest GitHub issue (#14)
	await processWarningDigest(env);

	// Write a daily marker to AE for historical tracking
	try {
		env.CF_MONITOR_AE.writeDataPoint({
			blobs: [env.ACCOUNT_NAME, 'system', 'daily-rollup'],
			doubles: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
			indexes: [`${env.ACCOUNT_NAME}:system:daily-rollup`],
		});
	} catch {
		// Best-effort
	}

	console.log(`[cf-monitor:rollup] Daily rollup complete for ${env.ACCOUNT_NAME}`);
}

/** Process yesterday's warning digest into a single GitHub issue. */
async function processWarningDigest(env: MonitorWorkerEnv): Promise<void> {
	if (!env.GITHUB_REPO || !env.GITHUB_TOKEN) return;

	// Use yesterday's date since this runs at midnight
	const yesterday = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10);
	const digestKey = `${KV.WARN_DIGEST}${yesterday}`;

	try {
		const rawDigest = await env.CF_MONITOR_KV.get(digestKey);
		if (!rawDigest) return;

		const digest: WarningDigestEntry[] = JSON.parse(rawDigest);
		if (digest.length === 0) return;

		// Group warnings by script
		const byScript = new Map<string, WarningDigestEntry[]>();
		for (const entry of digest) {
			const list = byScript.get(entry.script) ?? [];
			list.push(entry);
			byScript.set(entry.script, list);
		}

		// Format digest body
		const sections: string[] = [];
		for (const [script, warnings] of byScript) {
			sections.push(`### \`${script}\` (${warnings.length} warning${warnings.length > 1 ? 's' : ''})`);
			for (const w of warnings.slice(0, 20)) {
				sections.push(`- \`${w.message}\` — ${w.timestamp}`);
			}
			if (warnings.length > 20) {
				sections.push(`- _...and ${warnings.length - 20} more_`);
			}
		}

		const body = [
			`## Warning Digest: ${yesterday}`,
			`**Account**: ${env.ACCOUNT_NAME}`,
			`**Total warnings**: ${digest.length}`,
			`**Workers affected**: ${byScript.size}`,
			'',
			...sections,
			'',
			'---',
			'_Generated by cf-monitor daily rollup. These are P4 (informational) `console.warn()` entries._',
		].join('\n');

		await createGitHubIssue(env, {
			scriptName: env.ACCOUNT_NAME,
			outcome: 'warning' as never,
			priority: 'P4',
			fingerprint: `digest:${yesterday}`,
			errorMessage: `${digest.length} warnings across ${byScript.size} workers`,
			errorName: 'WarningDigest',
			isTransient: false,
			accountName: env.ACCOUNT_NAME,
			bodyOverride: body,
		});

		// Delete processed digest
		await env.CF_MONITOR_KV.delete(digestKey);

		console.log(`[cf-monitor:rollup] Warning digest created: ${digest.length} warnings from ${yesterday}`);
	} catch (err) {
		console.error(`[cf-monitor:rollup] Warning digest failed: ${err}`);
	}
}
