import pc from 'picocolors';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { parseYamlConfig } from '../yaml-parser.js';

interface DeployOptions {
	dryRun?: boolean;
}

export async function deployCommand(options: DeployOptions): Promise<void> {
	console.log(pc.bold('\ncf-monitor deploy\n'));

	const wranglerConfig = '.cf-monitor/wrangler.jsonc';

	if (!existsSync(wranglerConfig)) {
		console.error(pc.red('No .cf-monitor/wrangler.jsonc found. Run: npx cf-monitor init'));
		process.exit(1);
	}

	// Re-embed config from cf-monitor.yaml on every deploy
	const yamlPath = 'cf-monitor.yaml';
	if (existsSync(yamlPath)) {
		try {
			const yamlContent = readFileSync(yamlPath, 'utf-8');
			const configJson = parseYamlConfig(yamlContent);

			const wranglerContent = readFileSync(wranglerConfig, 'utf-8');
			const stripped = wranglerContent.replace(/^\s*\/\/.*$/gm, '');
			const wranglerObj = JSON.parse(stripped) as Record<string, unknown>;

			const vars = (wranglerObj.vars ?? {}) as Record<string, unknown>;
			vars.CF_MONITOR_CONFIG = configJson;
			wranglerObj.vars = vars;

			writeFileSync(
				wranglerConfig,
				`// Auto-generated by cf-monitor CLI — edit cf-monitor.yaml instead\n${JSON.stringify(wranglerObj, null, 2)}\n`
			);
			console.log(`  ${pc.green('✓')} Config embedded from ${yamlPath}`);
		} catch (err) {
			console.warn(pc.yellow(`  Warning: Could not embed config from ${yamlPath}: ${err}`));
		}
	}

	if (options.dryRun) {
		console.log(`  ${pc.yellow('Dry run')} — would deploy using ${wranglerConfig}`);
		return;
	}

	console.log('  Deploying cf-monitor worker...');

	try {
		const output = execFileSync('npx', ['wrangler', 'deploy', '-c', wranglerConfig], {
			encoding: 'utf-8',
			stdio: ['inherit', 'pipe', 'pipe'],
		});
		console.log(output);
		console.log(`  ${pc.green('✓')} cf-monitor worker deployed successfully`);
	} catch (err) {
		console.error(pc.red('\n  Deploy failed:'));
		console.error(err);
		process.exit(1);
	}

	console.log(`\n  Next: ${pc.cyan('npx cf-monitor wire --apply')} to auto-wire tail_consumers`);
}
