import type { MonitorWorkerEnv, TailOutcome } from '../../types.js';

export interface ErrorIssueParams {
	scriptName: string;
	outcome: TailOutcome;
	priority: string;
	fingerprint: string;
	errorMessage: string;
	errorName: string;
	isTransient: boolean;
	accountName: string;
	/** Override the issue body (e.g. for digest issues). */
	bodyOverride?: string;
}

/**
 * Create a GitHub issue for a captured error.
 * Uses a Personal Access Token (simpler than GitHub App).
 *
 * @returns The issue URL, or null if creation failed.
 */
export async function createGitHubIssue(
	env: MonitorWorkerEnv,
	params: ErrorIssueParams
): Promise<string | null> {
	if (!env.GITHUB_REPO || !env.GITHUB_TOKEN) return null;

	const labels = [
		`cf:error:${params.outcome}`,
		`cf:priority:${params.priority.toLowerCase()}`,
	];
	if (params.isTransient) labels.push('cf:transient');
	if (params.bodyOverride) labels.push('cf:digest');

	const title = `[${params.priority}] ${params.scriptName}: ${params.outcome}`;
	const body = params.bodyOverride ?? formatIssueBody(params);

	try {
		const response = await fetch(
			`https://api.github.com/repos/${env.GITHUB_REPO}/issues`,
			{
				method: 'POST',
				headers: {
					Authorization: `Bearer ${env.GITHUB_TOKEN}`,
					Accept: 'application/vnd.github+json',
					'Content-Type': 'application/json',
					'User-Agent': 'cf-monitor',
					'X-GitHub-Api-Version': '2022-11-28',
				},
				body: JSON.stringify({ title, body, labels }),
			}
		);

		if (!response.ok) {
			const text = await response.text();
			console.error(`[cf-monitor:github] Issue creation failed (${response.status}): ${text}`);
			return null;
		}

		const issue = await response.json() as { html_url: string };
		return issue.html_url;
	} catch (err) {
		console.error(`[cf-monitor:github] Issue creation error: ${err}`);
		return null;
	}
}

/** Escape markdown-active characters for safe interpolation in table cells. */
function escapeMd(s: string): string {
	return s.replace(/[|`\[\]()!*_~<>\\]/g, '\\$&');
}

function formatIssueBody(params: ErrorIssueParams): string {
	return `## Error Details

| Field | Value |
|-------|-------|
| **Worker** | \`${escapeMd(params.scriptName)}\` |
| **Outcome** | \`${escapeMd(params.outcome)}\` |
| **Priority** | ${escapeMd(params.priority)} |
| **Account** | ${escapeMd(params.accountName)} |
| **Transient** | ${params.isTransient ? 'Yes' : 'No'} |
| **Fingerprint** | \`${escapeMd(params.fingerprint)}\` |

### Error

\`\`\`
${params.errorName}: ${params.errorMessage}
\`\`\`

### Context

- **Detected by**: cf-monitor tail handler
- **Time**: ${new Date().toISOString()}
${params.isTransient ? '\n> This error matches a transient pattern. It may resolve on its own.' : ''}

---
*Generated by [cf-monitor](https://github.com/littlebearapps/cf-monitor)*`;
}
